[Build]
WithNetwork=true
Environment=KERNEL_CONFIG_SNIPPETS=kernel/gcp-pci.config

[Content]
BuildScripts=tdx-dummy/mkosi.build
PostInstallationScripts=tdx-dummy/mkosi.postinst

# Network packages
Packages=iproute2
         udhcpc
         dhcpcd5
         isc-dhcp-client
         ca-certificates
         curl
         wget
         net-tools

BuildPackages=ca-certificates
			  golang-go
			  git
