[Build]
WithNetwork=true
Environment=KERNEL_CONFIG_SNIPPETS=tdx-dummy/kernel.config

[Content]
BuildScripts=tdx-dummy/mkosi.build
BuildPackages=ca-certificates
			  golang-go
			  git
PostInstallationScripts=tdx-dummy/mkosi.postinst
